name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  CI: true

jobs:
  tests:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: App "job" - Install dependencies
        working-directory: ./job
        run: yarn install --frozen-lockfile

      - name: App "job" - TypeScript
        working-directory: ./job
        run: yarn tsc --noEmit --incremental

      - name: App "job" - Tests
        working-directory: ./job
        run: yarn test
